import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { getAllChapters, type ChapterMeta } from "./content";
import { getProjects, getRoadmaps, type Project } from "./projects";

function contentRoot(): string {
  const candidates = [resolve(process.cwd(), "..", "..", "content"), resolve(process.cwd(), "content")];
  const found = candidates.find(existsSync);
  if (!found) throw new Error("content/ not found");
  return found;
}

export interface DomainMeta {
  title: string;
  titleAr: string;
  blurb: string;
  blurbAr: string;
}

export interface DomainGroup {
  id: string;
  title: string;
  titleAr: string;
  blurb: string;
  blurbAr: string;
  domains: string[];
}

interface DomainsFile {
  groups: DomainGroup[];
  domains: Record<string, DomainMeta>;
}

let cache: DomainsFile | null = null;

function load(): DomainsFile {
  cache ??= JSON.parse(readFileSync(join(contentRoot(), "domains.json"), "utf8")) as DomainsFile;
  return cache;
}

export function getGroups(): DomainGroup[] {
  return load().groups;
}

export function getDomainMeta(domain: string): DomainMeta | undefined {
  return load().domains[domain];
}

export function getAllDomains(): string[] {
  return [...new Set(getAllChapters().map((c) => c.domain))];
}

/** Everything the platform holds on one topic — the answer to "what is here?" */
export interface TopicBundle {
  domain: string;
  meta: DomainMeta | undefined;
  chapters: ChapterMeta[];
  projects: Project[];
  roadmaps: { id: string; title: string; titleAr: string; phase: string }[];
  totalMinutes: number;
}

export function getTopic(domain: string): TopicBundle {
  const chapters = getAllChapters()
    .filter((c) => c.domain === domain)
    .sort((a, b) => a.order - b.order);

  const projects = getProjects().filter((p) => p.stack.includes(domain));

  const roadmaps: TopicBundle["roadmaps"] = [];
  for (const roadmap of getRoadmaps()) {
    for (const phase of roadmap.phases) {
      if (phase.chapters.some((id: string) => chapters.some((c) => c.contentId === id))) {
        roadmaps.push({
          id: roadmap.id,
          title: roadmap.title,
          titleAr: roadmap.titleAr,
          phase: phase.title,
        });
        break;
      }
    }
  }

  return {
    domain,
    meta: getDomainMeta(domain),
    chapters,
    projects,
    roadmaps,
    totalMinutes: chapters.reduce((sum, c) => sum + c.readingTime, 0),
  };
}

// ── Derived topics (§5.3) ───────────────────────────────────────────────────
// Generated by scripts/build-topics.mjs from real references in the corpus.
// Nothing here is hand-listed, so the topic count cannot drift ahead of the
// content it promises.

export interface GeneratedTopic {
  id: string;
  area: string;
  domain: string;
  title: string;
  titleAr: string;
  chapters: string[];
  labs: string[];
  roadmaps: string[];
  projects: string[];
}

export interface TopicArea {
  id: string;
  title: string;
  titleAr: string;
}

let topicCache: { areas: TopicArea[]; topics: GeneratedTopic[] } | null = null;

function loadTopics() {
  if (!topicCache) {
    const file = join(contentRoot(), "topics.generated.json");
    topicCache = existsSync(file)
      ? (JSON.parse(readFileSync(file, "utf8")) as { areas: TopicArea[]; topics: GeneratedTopic[] })
      : { areas: [], topics: [] };
  }
  return topicCache;
}

export function getTopicAreas(): TopicArea[] {
  return loadTopics().areas;
}

export function getGeneratedTopics(): GeneratedTopic[] {
  return loadTopics().topics;
}

export function getGeneratedTopic(id: string): GeneratedTopic | undefined {
  return loadTopics().topics.find((t) => t.id === id);
}
