import { AlertTriangle, Cloud, ExternalLink, Monitor, Terminal } from "lucide-react";

/**
 * Where a lab can be performed.
 *
 * Three peers — a hosted sandbox, the learner's own machine, and their cloud
 * account — because a lab can offer several at once and an earlier shape that
 * treated Killercoda as the main path could not say so.
 *
 * They are not shown as three equal buttons. Whichever demands least of the
 * learner becomes the primary action and the rest sit beneath it, so a
 * beginner is told what to do rather than asked to choose between three
 * unfamiliar words.
 *
 * EgyKode is a static export: this renders a link, a list of requirements and
 * a note. Nothing here provisions anything, holds a credential, or learns what
 * happened afterwards.
 */
/**
 * The standalone lab-environment repository.
 *
 * Not the main EgyKode repository, which is 6.4M of website around 97K of
 * environment — a learner cloning it downloads seventy times what they need,
 * and reasonably wonders why a Linux lab ships a Next.js site.
 *
 * Its contents are generated by `scripts/sync-lab-env.mjs`, and `npm run
 * lint:lab-env` fails when the mirror drifts from the sources here.
 */
const LAB_ENV_REPO = "https://github.com/Waleeddarwesh/EgyKode-lab";

export function HandsOn({
  online,
  local,
  cloud,
  tier,
  labels,
}: {
  online?: { enabled: boolean; url?: string };
  local?: {
    enabled: boolean;
    environment?: string;
    tools?: string[];
    capabilities?: string[];
    note?: string;
  };
  cloud?: { enabled: boolean; requiresOwnAccount: boolean };
  tier: "guided" | "challenge" | "incident";
  labels: {
    heading: string;
    onlineTitle: string;
    onlineBody: string;
    onlineCta: string;
    onlineCtaChallenge: string;
    onlineOpensIn: string;
    onlinePending: string;
    localTitle: string;
    localBody: string;
    localCta: string;
    localNeeds: string;
    localFirstRun: string;
    cloudTitle: string;
    cloudBody: string;
    verifyNote: string;
  };
}) {
  // Re-checked here as well as in content lint, because a link built from data
  // should never be able to point somewhere unexpected.
  const onlineReady =
    online?.enabled && online.url && /^https:\/\/(www\.)?killercoda\.com\//.test(online.url);
  const localReady = Boolean(local?.enabled);
  const cloudReady = Boolean(cloud?.enabled);

  // Nothing to offer at all: render nothing rather than a paragraph explaining
  // an absence on every page a learner opens.
  if (!onlineReady && !localReady && !cloudReady && !online) return null;

  // Least friction wins the primary slot: a hosted terminal needs nothing
  // installed, a local run needs tools, and a cloud run needs an account and a
  // card.
  const primary = onlineReady ? "online" : localReady ? "local" : "cloud";

  return (
    <section className="card mt-8 p-6" aria-labelledby="hands-on">
      <p
        id="hands-on"
        className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide"
        style={{ color: "var(--clr-primary-dark)" }}
      >
        <Terminal size={14} aria-hidden />
        {labels.heading}
      </p>

      {/* ── Online ────────────────────────────────────────────────────────── */}
      {onlineReady && (
        <div className="mt-4">
          <p className="text-sm leading-relaxed text-content-secondary">{labels.onlineBody}</p>
          <a
            href={online?.url}
            target="_blank"
            rel="noopener noreferrer"
            className={`btn mt-4 h-11 px-6 ${primary === "online" ? "btn-primary" : "btn-outline"}`}
          >
            {tier === "guided" ? labels.onlineCta : labels.onlineCtaChallenge}
            <ExternalLink size={15} aria-hidden />
          </a>
          {/* Named, not hidden. A button that silently moves someone onto
              another company's site is worse than one that says where it goes. */}
          <p className="mt-2 text-xs text-content-muted">{labels.onlineOpensIn}</p>
        </div>
      )}

      {/* A scenario exists but is unpublished — and worth saying only when
          there is nothing else on offer.
          Every lab carries `online.enabled: false` until its Killercoda
          scenario is published, so this once rendered on all 114 pages: a
          learner arrived, read that their environment "is being prepared", and
          only then found a working local option underneath. The apology came
          first and the answer second. Where another option exists, that option
          is the answer, and this says nothing. */}
      {!onlineReady && online && !online.enabled && !localReady && !cloudReady && (
        <p className="mt-4 text-sm leading-relaxed text-content-secondary">{labels.onlinePending}</p>
      )}

      {/* ── Local ─────────────────────────────────────────────────────────── */}
      {/* The divider follows what rendered, not what exists. Keyed on `online`
          it drew a separator under an empty space on every lab, because every
          lab has an `online` block whether or not it displays anything. */}
      {localReady && (
        <div className={onlineReady ? "mt-6 border-t pt-5" : "mt-4"}>
          <p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-content-muted">
            <Monitor size={13} aria-hidden />
            {labels.localTitle}
          </p>
          <p className="mt-2 text-sm leading-relaxed text-content-secondary">{labels.localBody}</p>

          {/* Placed above the tools and the command, not below them: this is
              what decides whether a learner should pick this path at all, and
              it is useless once they have already run it. */}
          {local?.note && (
            <p
              className="mt-3 flex gap-2 rounded-md px-3 py-2 text-xs leading-relaxed"
              style={{ background: "var(--clr-warning-bg)", color: "var(--clr-warning)" }}
            >
              <AlertTriangle size={13} className="mt-px shrink-0" aria-hidden />
              <span>{local.note}</span>
            </p>
          )}

          {local?.tools && local.tools.length > 0 && (
            <>
              <p className="mt-3 text-xs text-content-muted">{labels.localNeeds}</p>
              <ul className="mt-2 flex flex-wrap gap-2">
                {local.tools.map((tool) => (
                  <li
                    key={tool}
                    className="badge border px-2.5 py-1 font-mono text-xs text-content-secondary"
                  >
                    {tool}
                  </li>
                ))}
              </ul>
            </>
          )}

          {/* The whole sequence, not just the last line of it.
              This showed `./egykode start` alone, which means "run the file
              named egykode in this directory" — and the reader has no such
              directory and no such file. The one instruction that made the
              other two work was the one missing, so the command could only be
              followed by someone who already knew what it needed.
              The clone is included every time rather than hidden behind a
              "first time?" toggle: it costs two lines, and a reader who
              already has the repository loses nothing by seeing them. */}
          <pre className="mt-3 overflow-x-auto rounded-md border px-3 py-2 font-mono text-xs leading-relaxed text-content-secondary">
            <code>
              {[
                `git clone ${LAB_ENV_REPO}.git`,
                `cd ${LAB_ENV_REPO.split("/").pop()}`,
                local?.environment && local.environment !== "base"
                  ? `./egykode start ${local.environment}`
                  : "./egykode start",
                // The sequence stopped here, at a command whose entire output
                // is "Ready" — leaving the reader with a running environment,
                // no prompt, and a page full of commands to run in it.
                "./egykode shell",
                // Service labs run on the node, not the controller: the
                // controller has no init system, and `systemctl` there fails
                // with a message about the bus that reads as a permissions
                // problem and is not one.
                ...(local?.capabilities?.includes("init-system") ? ["ssh node1"] : []),
              ].join("\n")}
            </code>
          </pre>
          <p className="mt-2 text-xs leading-relaxed text-content-muted">{labels.localFirstRun}</p>
          <p className="mt-2 text-xs text-content-muted">{labels.localCta}</p>
        </div>
      )}

      {/* ── Cloud ─────────────────────────────────────────────────────────── */}
      {cloudReady && (
        <div className={onlineReady || localReady ? "mt-6 border-t pt-5" : "mt-4"}>
          <p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-content-muted">
            <Cloud size={13} aria-hidden />
            {labels.cloudTitle}
          </p>
          <p className="mt-2 text-sm leading-relaxed text-content-secondary">{labels.cloudBody}</p>
        </div>
      )}

      {/* The site cannot see into any of these. Ticking a criterion stays the
          learner's own claim, which keeps the evidence labels above honest. */}
      <p className="mt-5 border-t pt-4 text-xs leading-relaxed text-content-muted">
        {labels.verifyNote}
      </p>
    </section>
  );
}
